# Generated by Django 5.0.6 on 2024-05-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
